default: &default
  adapter: mysql2
  pool: 5
  timeout: 5000
  encoding: utf8
  reconnect: true
  database: personalgifter_development
  username: root
  password: 
  socket: /tmp/mysql.sock

development:
  <<: *default
  
production:
  adapter: mysql2
  encoding: utf8
  reconnect: true
  database: personalgifter_production
  pool: 5
  username: root
  password: pg.0910.db!
  socket: /var/run/mysqld/mysqld.sock
  port: 3306

test:
  default: &default
  adapter: mysql2
  pool: 5
  timeout: 5000
  encoding: utf8
  reconnect: true
  database: personalgifter_test
  username: root
  password: 
  socket: /tmp/mysql.sock