# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 64507a47ba3962d77da5358cb8343159e5c8508aca38e4068b725864e1258b39ba334e12a68f4143f1468cc2e966bef7b27c453cd9909e29fa45f32baf5ee2af

test:
  secret_key_base: a48144bdae7cab4b572aa7ed4a0bd76e503778066c3cc887cc9a614c38a0138555a1b78fd496d1d76a67ccd573b46f083111bf3b81058405f9ad8821b40cb9a5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
