# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
Occasion.create!(:name => 'cumpleaños')
Occasion.create!(:name => 'boda')
Occasion.create!(:name => 'aniversario')
Occasion.create!(:name => 'dia de')
Occasion.create!(:name => 'bautismo')
Occasion.create!(:name => 'babyshower')
Occasion.create!(:name => 'se muda')
Occasion.create!(:name => 'se van a vivir juntos')
Occasion.create!(:name => 'inauguran casa o reforma')
Occasion.create!(:name => 'inauguran emprendimiento')
Occasion.create!(:name => 'por darle un gusto')
Occasion.create!(:name => 'para darle una sorpresa, sin motivo concreto')
Occasion.create!(:name => 'para reconciliarse')
Occasion.create!(:name => 'porque yo lo valgo!')
Occasion.create!(:name => 'navidad')
Occasion.create!(:name => 'reyes')
Occasion.create!(:name => 'recibimiento')
Occasion.create!(:name => 'empresarial')
Occasion.create!(:name => 'otro evento familiar')
Occasion.create!(:name => 'amigo invisible')
Occasion.create!(:name => 'festividad religiosa')
Interest.create!(:name => 'CREATIVO, CHISPEANTE, DIVERTIDO, ORIGINAL')
Interest.create!(:name => 'ATLÉTICO, DEPORTISTA, CUIDADOSA DEL FÍSICO, DE VIDA SALUDABLE, GUSTA DE LAS CAMINATAS, ANDAR EN BICI, VIDA AL AIRE LIBRE')
Interest.create!(:name => 'REBELDE, DESCONTRACTURADO, JUVENIL, INFORMAL')
Interest.create!(:name => 'ACOGEDOR, FAMILIERO, CALIDO, PADRE O MADRE DE FAMILIA, CARIÑOSO, ROMÁNTICO, BUEN COCINERO')
Interest.create!(:name => 'INNOVADOR, ATENTO A LAS TENDENCIAS, TECHIE, EMPRENDEDOR, VANGUARDISTA, ATENTO AL DISEÑO, INDEPENDIENTE')
Interest.create!(:name => 'REFINADO, ELEGANTE, SIEMPRE IMPECABLE, FORMAL, CUIDADOSO DE SU APARIENCIA, NO OSTENTOSO')
Interest.create!(:name => 'EXTROVERTIDO, SALIDOR, DE ASISTIR A MUCHAS REUNIONES SOCIALES, CON MUCHOS GRUPOS DE AMIGOS')
Interest.create!(:name => 'ESPIRITUAL, MÍSTICO, RELIGIOSO, SENSIBLE')
Interest.create!(:name => 'CON ESTILO, PREOCUPADO POR LA MODA Y APARIENCIA')
Interest.create!(:name => 'EXPLORADOR, VIAJERO, AVENTURERO')
Interest.create!(:name => 'NATURALISTA, DEFENSOR DE CAUSAS, LUCHADOR SOCIAL')
Interest.create!(:name => 'INTELECTUAL, PROFESIONAL, ESTUDIOSO, LECTOR, INTROVERTIDO')
Interest.create!(:name => 'INTERESADA POR LOS PRODUCTOS ARTESANALES, HECHOS A MANO, ÚNICOS')
Interest.create!(:name => 'INTERESADA POR LOS PRODUCTOS INDUSTRIALES DE BUEN DISEÑO')
Interest.create!(:name => 'APRECIA LOS PRODUCTOS PARA EL HOGAR')
Interest.create!(:name => 'PREFIERE EXPERIENCIAS, MOMENTOS O PRODUCTOS PARA COMPARTIR')
Interest.create!(:name => 'ADORA LA ROPA Y LOS ACCESORIOS DE VESTIR')
Relationship.create!(:name => 'PAREJA')
Relationship.create!(:name => 'HIJO/A')
Relationship.create!(:name => 'MADRE/PADRE')
Relationship.create!(:name => 'ABUELO/A')
Relationship.create!(:name => 'SOBRINO')
Relationship.create!(:name => 'SUEGROS')
Relationship.create!(:name => 'FAMILIA DIRECTA')
Relationship.create!(:name => 'FAMILIA LEJANA')
Relationship.create!(:name => 'AMIGO')
Relationship.create!(:name => 'MEJOR AMIGO')
Relationship.create!(:name => 'CONOCIDO')
Relationship.create!(:name => 'HIJO DE AMIGO')
Relationship.create!(:name => 'HIJO DE MEJOR AMIGO')
Relationship.create!(:name => 'COMPAÑERO DE TRABAJO')
Relationship.create!(:name => 'JEFE')
Relationship.create!(:name => 'UN COMPROMISO')
Relationship.create!(:name => 'CLIENTES')
Relationship.create!(:name => 'EMPLEADOS')
Target.create!(:name => 'Niños y adolescentes')
Target.create!(:name => 'Jóvenes')
Target.create!(:name => 'Adultos')
Target.create!(:name => 'Seniors')
Genre.create!(:name => 'Mujer')
Genre.create!(:name => 'Hombre')

Product.create!(:name => 'PERCHERO FLIP MADERA NATURAL PERCHAS NEGRAS', :description => 'PERCHERO DE PARED CON 5 PERCHAS RETRÁCTILES', :price => '1699', :link => 'http://www.altamiraoe.uy/perchero-de-pared-flip-natural-5-perchas.html')
Product.create!(:name => 'SET DE PING PONG PONGO', :description => 'SET DE PING PONG', :price => '2190', :link => 'http://www.altamiraoe.uy/set-de-ping-pong-portatil-pongo-surf-blue.html')
Product.create!(:name => 'CLOTHESLINE', :description => 'PORTARRETRATO', :price => '1399', :link => 'http://www.altamiraoe.uy/portarretrato-multiple-de-pared-clothesline.html')
Product.create!(:name => 'CONCEAL', :description => 'REPISA', :price => '599', :link => 'http://www.altamiraoe.uy/repisa-conceal-large.html')
Product.create!(:name => 'TOLOMEO MINI NICKEL O NEGRO', :description => 'LAMPARA', :price => '2490', :link => 'http://www.altamiraoe.uy/lampara-escritorio-tolomeo-mini-silver-e14.html')
Product.create!(:name => 'T-shirt con estampa de inspiracion mandala azul francia', :description => 'T-shirt Manga corta con escote redondo, estampa de inspiracion mandala y brillos aplicados. 100% Poliester', :price => '2490', :link => 'http://lolita.com.uy/catalogo/t-shirt-con-estampa-de-inspiracion-mandala-azul-francia_KC16.06R_5')
Product.create!(:name => 'PORTABOTELLAS PARA BICICLETA', :description => 'PORTABOTELLAS PARA BICICLETA', :price => '19', :link => 'http://gron.bigcartel.com/product/24-bottles-porta-bottiglia')
Product.create!(:name => 'BOTELLA PARA DEPORTES', :description => 'BOTELLA PARA DEPORTES', :price => '25', :link => 'http://gron.bigcartel.com/product/24-bottles-dispenser-bottle')
Product.create!(:name => 'JARRO TÉRMICO', :description => 'JARRO TÉRMICO HERMÉTICO PARA FRIIO Y CALOR', :price => '1590', :link => 'http://www.altamiraoe.uy/jarro-termico-west-loop-2-latte-matte.html')
Product.create!(:name => 'SET DE IDENTIFICADOR DE COPAS + TAPÓN', :description => 'TAPÓN, SET DE IDENTIFICADORES Y TAPÓN DE SILICONA', :price => '1590', :link => 'http://www.altamiraoe.uy/identificador-de-copas-tapon-de-botellas-glasses.html')
Product.create!(:name => 'SET DE CHOCOLATES BELGAS', :description => 'CHOCOLATES', :price => '1590', :link => 'http://www.bigbox.com.uy/regalos/gastronomia/box-delices-uruguay/cho-chocolate-belga')
Product.create!(:name => 'SOBRE TABLET CITY GRID', :description => 'ESTUCHE PARA TABLET', :price => '990', :link => 'http://www.builtny.com.uy/productosb/tablet-laptop/sobre-tablet-city-grid-detail')
Product.create!(:name => 'ESTUCHE PARA CHUPETE BABY PINK STRIPE', :description => 'ESTUCHE PARA CHUPETE', :price => '279', :link => 'http://www.builtny.com.uy/productosb/baby-line/estuche-para-chupete-baby-pink-stripe-detail')
Product.create!(:name => 'ESTUCHE PARA CHUPETE BLUE STRIPE', :description => 'ESTUCHE PARA CHUPETE', :price => '279', :link => 'http://www.builtny.com.uy/productosb/baby-line/estuche-para-chupete-blue-stripe-detail')
Product.create!(:name => 'BOLSA DE BEBE ESENCIALES CADDY', :description => 'BOLSA ORGANIZADORA PARA IMPLEMENTOS DE BEBE', :price => '1599', :link => 'http://www.builtny.com.uy/productosb/baby-line/bolsa-de-bebe-esenciales-caddy-detail')
Product.create!(:name => 'LUNCHERA GOURMET GETAWAY MULTICOLOR FLOWERS', :description => 'LUNCHERA', :price => '990', :link => 'http://www.builtny.com.uy/productosb/luncheras/lunchera-gourmet-getaway-multicolor-flowers-detail')
Product.create!(:name => 'CAJA DE ALMUERZO MINIDOT', :description => 'LUNCHERA', :price => '699', :link => 'http://www.builtny.com.uy/nuevosb/caja-de-almuerzo-mini-dot-detail')
Product.create!(:name => 'MÁSCARA PARA OJOS AFUERA LUZ', :description => 'TAPAOJOS PARA VIAJE', :price => '399', :link => 'http://www.builtny.com.uy/nuevosb/mascara-para-los-ojos-afuera-luz-detail')
Product.create!(:name => 'CROCS', :description => 'ZAPATOS', :price => '990', :link => 'http://www.toto.com.uy/index.php/hombres/crocs')

